export type Product={asin:string;slug:string;brand:string;name:string;category:'matratze'|'zubehoer';kind:string;size:string;height?:number;firmness?:string[];material?:string;features:string[];caveat:string;source:string;verifiedAt:string};
export const products:Product[]=[
{asin:'B07QY18HWP',slug:'traeumegut24-aquaflex-ortho',brand:'Träumegut24',name:'AquaFlex Ortho',category:'matratze',kind:'Kaltschaum',size:'90 × 200 cm',height:12,firmness:['H2','H3'],material:'Kaltschaum',features:['Wendbarer Härtegrad','7-Zonen-Aufbau','Abnehmbarer Bezug'],caveat:'Die 12 cm Höhe kann für Personen mit Wunsch nach einer hohen Matratze zu niedrig sein.',source:'https://www.shareofclicks.com/brand/tr%C3%A4umegut24/de/products',verifiedAt:'2026-09-24'},
{asin:'B0C8Z79P4L',slug:'bmm-ortho-medic',brand:'BMM',name:'Ortho Medic',category:'matratze',kind:'Taschenfederkern',size:'90 × 200 cm',height:21,firmness:['H3'],material:'Taschenfederkern',features:['7-Zonen-Aufbau','Abnehmbarer Bezug','Federkern'],caveat:'Nur der recherchierte Härtegrad H3 ist für diese Variante belegt.',source:'https://www.matelas-experience.com/showroom/d/produits-services/bmm-matelas-ortho-medic-90x200-cm-avec-noyau-a-ressorts-ensaches-niveau-de-fermete-h3certifie-oko-texmatelas-ergonomique-a-7-zones-hauteur-21-cmmatelas-fabriques-en-allemagne-90-x-200-cm-h3',verifiedAt:'2026-09-24'},
{asin:'B07ZRQFB5S',slug:'emma-one',brand:'Emma',name:'One',category:'matratze',kind:'Kaltschaum',size:'90 × 200 cm',height:18,firmness:['H2'],material:'Kaltschaum',features:['3-Zonen-Stützung','Waschbarer Bezug'],caveat:'Die genaue Härte hängt von der gewählten Amazon-Variante ab.',source:'https://www.amazon.de/Emma-Kaltschaummatratze-Mittelhart-3-Zonen-St%C3%BCtzung-Atmungsaktiver/dp/B07ZRQFB5S',verifiedAt:'2026-09-24'},
{asin:'B01N6QMZED',slug:'traumnacht-premium-taschenfederkern',brand:'Traumnacht',name:'Premium 7-Zonen',category:'matratze',kind:'Taschenfederkern',size:'140 × 200 cm',firmness:['H3'],material:'Taschenfederkern',features:['7-Zonen-Aufbau','Federkern'],caveat:'Höhe und Bezugseigenschaften sind für diese Variante noch nicht geprüft.',source:'https://www.mex.de/produkt/traumnacht-orthopaedische-7-zonen-tonnen-b01n6qmzed',verifiedAt:'2026-09-24'},
{asin:'B09XR49YJF',slug:'utopia-bedding-matratzenauflage',brand:'Utopia Bedding',name:'Gesteppte Matratzenauflage',category:'zubehoer',kind:'Matratzenschoner',size:'140 × 200 cm',material:'Mikrofaser',features:['Eckbänder','Gesteppte Auflage'],caveat:'Die genauen Pflegeangaben bitte beim aktuellen Angebot prüfen.',source:'https://www.merchantwords.com/asin/de/B09XR49YJF',verifiedAt:'2026-09-24'},
{asin:'B09C8L2YJF',slug:'smartsleep-recovery-pillow',brand:'smartsleep',name:'Recovery Pillow',category:'zubehoer',kind:'Nackenstützkissen',size:'Größe beim Angebot prüfen',material:'Viscoschaum',features:['Kopfmulde','Formkissen'],caveat:'Die passende Kissenhöhe ist individuell; genaue Maße beim Anbieter prüfen.',source:'https://m.media-amazon.com/images/I/41X1dlQFLTL.pdf',verifiedAt:'2026-09-24'}
];
export const mattresses=products.filter(p=>p.category==='matratze');
export const accessories=products.filter(p=>p.category==='zubehoer');
export const bySlug=(slug:string)=>products.find(p=>p.slug===slug);
export const affiliateUrl=(asin:string)=>`https://www.amazon.de/dp/${asin}?tag=onlinestarkei-21`;
