export type Product={asin:string;slug:string;brand:string;name:string;category:'matratze'|'zubehoer';kind:string;size:string;height?:number;firmness?:string[];material?:string;features:string[];caveat:string;source:string;verifiedAt:string};
export const products:Product[]=[
{asin:'B07QY18HWP',slug:'traeumegut24-aquaflex-ortho',brand:'Träumegut24',name:'AquaFlex 7-Zonen',category:'matratze',kind:'Kaltschaum',size:'90 × 200 cm',height:12,firmness:['H2','H3'],material:'Kaltschaum',features:['Härtegrade H2 / H3','7-Zonen-Aufbau','Abnehmbarer Bezug'],caveat:'Die 12 cm Höhe kann für Personen mit Wunsch nach einer hohen Matratze zu niedrig sein.',source:'https://www.amazon.de/dp/B07QY18HWP',verifiedAt:'2026-10-08'},
{asin:'B0C8Z79P4L',slug:'bmm-ortho-medic',brand:'BMM',name:'Ortho Medic',category:'matratze',kind:'Taschenfederkern',size:'90 × 200 cm',height:21,firmness:['H3'],material:'Taschenfederkern',features:['7-Zonen-Aufbau','Abnehmbarer Bezug','Federkern'],caveat:'Nur der recherchierte Härtegrad H3 ist für diese Variante belegt.',source:'https://www.amazon.de/dp/B0C8Z79P4L',verifiedAt:'2026-10-08'},
{asin:'B07ZRQFB5S',slug:'emma-one',brand:'Emma',name:'One',category:'matratze',kind:'Kaltschaum',size:'90 × 200 cm',height:18,firmness:['H2'],material:'Kaltschaum',features:['3-Zonen-Stützung','Waschbarer Bezug'],caveat:'Die genaue Härte hängt von der gewählten Amazon-Variante ab.',source:'https://www.amazon.de/dp/B07ZRQFB5S',verifiedAt:'2026-10-08'},
{asin:'B01N6QMZED',slug:'traumnacht-premium-taschenfederkern',brand:'Traumnacht',name:'Basic 7-Zonen',category:'matratze',kind:'Taschenfederkern',size:'140 × 200 cm',height:16,firmness:['H3'],material:'Taschenfederkern',features:['7-Zonen-Aufbau','Federkern','Abnehmbarer Bezug'],caveat:'Die verlinkte ASIN bezeichnet aktuell die Basic-Variante mit 16 cm Höhe. Modellname und Variante vor dem Kauf prüfen.',source:'https://www.amazon.de/dp/B01N6QMZED',verifiedAt:'2026-10-08'},
{asin:'B09XR49YJF',slug:'utopia-bedding-matratzenauflage',brand:'Utopia Bedding',name:'Gesteppte Matratzenauflage',category:'zubehoer',kind:'Matratzenschoner',size:'140 × 200 cm',material:'Polyester',features:['Eckbänder','Gesteppte Auflage'],caveat:'Die genauen Pflegeangaben bitte beim aktuellen Angebot prüfen.',source:'https://www.amazon.de/dp/B09XR49YJF',verifiedAt:'2026-10-08'},
{asin:'B09C8L2YJF',slug:'smartsleep-recovery-pillow',brand:'smartsleep',name:'Recovery Pillow',category:'zubehoer',kind:'Nackenstützkissen',size:'Größe beim Angebot prüfen',material:'Viscoschaum',features:['Kopfmulde','Formkissen'],caveat:'Die passende Kissenhöhe ist individuell; genaue Maße beim Anbieter prüfen.',source:'https://www.amazon.de/dp/B09C8L2YJF',verifiedAt:'2026-10-08'}
];
export const mattresses=products.filter(p=>p.category==='matratze');
export const accessories=products.filter(p=>p.category==='zubehoer');
export const bySlug=(slug:string)=>products.find(p=>p.slug===slug);
export const affiliateUrl=(asin:string)=>`https://www.amazon.de/dp/${asin}?tag=onlinestarkei-21`;
